name: Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        brew install cmake pkg-config libsndfile googletest swift
    
    - name: Create test fixtures
      run: |
        mkdir -p tests/fixtures/input
        mkdir -p tests/fixtures/output
        # Create simple test files
        chmod +x tests/fixtures/create_simple_fixtures.sh
        ./tests/fixtures/create_simple_fixtures.sh
    
    - name: Configure and build C++ application
      run: |
        mkdir -p build
        cd build
        cmake .. -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug
        make -j$(sysctl -n hw.ncpu)
    
    - name: Run C++ tests (if available)
      run: |
        cd build
        if [ -f "tests/cpp/m8_formatter_tests" ]; then
          ./tests/cpp/m8_formatter_tests --gtest_output=xml:test_results.xml
        else
          echo "C++ tests not available, skipping"
        fi
    
    - name: Build Swift package
      run: |
        swift build --package-path . -c debug
    
    - name: Run Swift tests
      run: |
        swift test --package-path . -c debug
    
    - name: Run integration tests
      run: |
        # Test the complete application
        ./build/M8SampleFormatter tests/fixtures/input tests/fixtures/output
        
        # Test with different options
        ./build/M8SampleFormatter tests/fixtures/input tests/fixtures/output --no-bitdepth
        ./build/M8SampleFormatter tests/fixtures/input tests/fixtures/output --flatten-folders
    
    - name: Test GUI application
      run: |
        # Build and test the GUI
        swift build --package-path . -c release --product M8FormatterGUI
        ./scripts/build_app_bundle.sh
        
        # Test that the app bundle was created
        test -f M8SampleFormatter.app/Contents/MacOS/M8SampleFormatter
    
    - name: Run performance tests
      run: |
        # Test processing speed
        time ./build/M8SampleFormatter tests/fixtures/input tests/fixtures/output
        
        # Test memory usage if leaks is available
        if command -v leaks >/dev/null 2>&1; then
          leaks --atExit -- ./build/M8SampleFormatter tests/fixtures/input tests/fixtures/output || echo "Memory test completed"
        fi
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          build/test_results.xml
          build/
    
    - name: Upload app bundle
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: app-bundle
        path: M8SampleFormatter.app
